### ISSUE TITLE
Check tech/tech detail to be sure they are valid

### ISSUE THREAD

**Issue by gschivley** [PowerGenome/PowerGenome#122]
If a tech_detail (possibly also tech) are misspelled, the `new_gen_df` in `nrelatb.py` will have `NaN` values. But the error is only raised when calculating investment costs so it is hard for a user to understand why their investment costs contain `NaN` values.

Check this in the `util.check_settings` function?

**Comment by annafjacobson** [comment]
Happy to take a look! I should have time tomorrow or Friday.
