### ISSUE TITLE
Fiona & Numpy Version Error

### ISSUE THREAD

**Issue by Msypa7** [PowerGenome/PowerGenome#241]
<img width="808" alt="Screen Shot 2022-12-16 at 11 22 52 AM" src="https://user-images.githubusercontent.com/121686524/210095515-96262ad7-16a3-438d-9c50-ba9f6fb9a2ad.png">
<img width="875" alt="Screen Shot 2022-12-30 at 11 19 14 AM" src="https://user-images.githubusercontent.com/121686524/210095564-74d7e6c0-2143-439e-96da-e425b482fb0f.png">

Had Fiona version 1.8.20 and numpy version 1.24.0.
We received the attached errors and resolved errors by changing to Fiona 1.8.22 and numpy 1.23.5.

**Comment by gschivley** [comment]
Hi, sorry for the delay over the new year. To clarify, was the first set of errors with Fiona 1.8.20/numpy 1.24.0 and the second set with Fiona 1.8.22/numpy 1.23.5? I'm seeing that [other projects](https://github.com/numba/numba/issues/8615#issuecomment-1357865375) are also reporting the `SystemError: initialization of _internal failed without raising an exception` message from numba with numpy 1.24.0.

**Comment by Msypa7** [comment]
Hi Greg, 

The first set of errors was from having numpy 1.24.0, which is the SystemError: initialization of _internal failed without raising an exception. Once I changed the numpy version to 1.23.5, I no longer got that error message. Then, I got the error regarding fiona, which was the import error. This error was fixed by changing Fione to 1.8.22. I hope that clears things up, sorry if it was unclear. 

Best, 
Michael Sypa

**Comment by Msypa7** [comment]
Hi Greg,

The first set of errors was from having numpy 1.24.0, which is the
SystemError: initialization of _internal failed without raising an
exception. Once I changed the numpy version to 1.23.5, I no longer got that
error message. Then, I got the error regarding fiona, which was the import
error. This error was fixed by changing Fione to 1.8.22. I hope that clears
things up, sorry if it was unclear.

Best,
Michael Sypa

**Comment by gschivley** [comment]
Ahh, got it. Thanks for the info!

**Comment by gschivley** [comment]
@Msypa7 are you on a mac with M1 processor? If so, do you mind [opening an issue](https://github.com/Toblerity/Fiona/issues) with Fiona? On existing issues that mention this problem they say to install from conda-forge, which is what we're doing.
