### ISSUE TITLE
Merge Error After Pulling Most Recent Changes

### ISSUE THREAD

**Issue by Msypa7** [PowerGenome/PowerGenome#244]
<img width="796" alt="Screen Shot 2023-01-20 at 11 16 13 AM" src="https://user-images.githubusercontent.com/121686524/213750706-8e0df31a-7cd3-485b-bdab-4eacd5437312.png">

**Comment by gschivley** [comment]
Thanks for reporting the bug. I'm working to figure out where a couple units are getting duplicated so I can patch it.

In the future, it's helpful if you give some additional information like the model regions that you're using. I didn't hit this bug with the CA_AZ example system but I did hit it with ISONE.

I've pushed a fix to the `develop` branch. Can you test your system there to confirm it works?

**Comment by Msypa7** [comment]
Sorry for not being more specific about which test system I used. I will definitely make sure to give more information when posting about issues in the future. After pulling the commits from the develop branch, I was able to run PowerGenome successfully for the CA_AZ example system, which I previously got the MergeError from. I have not tried ISONE, but I can try that region as well.

**Comment by gschivley** [comment]
This was fixed with #243
