### ISSUE TITLE
CO₂ pipeline costs ignored when also using EFS flexible resources

### ISSUE THREAD

**Issue by gschivley** [PowerGenome/PowerGenome#274]
When specifying flexible resources like EVs or heat pumps, the resulting data frame has all possible output columns specified in the settings. This causes an issue when merging in CO₂ pipeline costs. I've [fixed the issue](bfce3590d7f2ca88b74878bab82e359f273fef16) in `develop` but still need to merge into `master` and create a version release.

**Comment by ani-mohan** [comment]
Should line 133 in co2_pipeline_cost.py be: 
df = df.reset_index(drop=True)?

drop=True is currently missing and it throws an error when trying to reset the index.

**Comment by gschivley** [comment]
Fixed with #281
