### ISSUE TITLE
Resource Group Profiles path

### ISSUE THREAD

**Issue by nspatank** [PowerGenome/PowerGenome#275]
Even after specifying the `Resource_Group_Profiles` variable in the `env.yml` file, we received the following error:

OSError: Passed non-file path: /Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/PowerGenome_Resource_Groups/resource_groups/ipm_regions/interpolated_scaled_offshore_wind_profiles_20210713.parquet

Here are the full contents of the env.yml file:
PUDL_DB: "sqlite://///Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/PUDL_Data/pudl.sqlite"
PG_DB: "sqlite://///Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/pg_misc_tables_efs.sqlite"
EFS_DATA: "/Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/efs_files_utc/"
DISTRIBUTED_GEN_DATA: "/Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/cambium_dg_data/"
RESOURCE_GROUPS: "/Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/PowerGenome_Resource_Groups/resource_groups/ipm_regions/"
RESOURCE_GROUP_PROFILES: "/Users/npatankar/D/PowerGenome/data/PowerGenome_Data_Files/PowerGenome_Resource_Groups/generation_profiles/"

**Comment by gschivley** [comment]
Looks like I didn't properly use parameters in `settings` instead of `SETTINGS` (the .env file) in all cases. For now can you add `RESOURCE_GROUP_PROFILES` to your .env file?

**Comment by nspatank** [comment]
For now, I have moved the contents of the `RESOURCE_GROUP_PROFILES `to the `RESOURCE_GROUP` folder. It works well. But it would be helpful to have a separate directory for resource profiles.

**Comment by gschivley** [comment]
I have a fix started in #277
