### ISSUE TITLE
CA_AZ Example Test System Outdated

### ISSUE THREAD

**Issue by sierra-e** [PowerGenome/PowerGenome#299]
The renewable resources clusters tag in example system is no longer compatible with PowerGenome
Error message: KeyError: "None of ['id'] are in the columns"

**Comment by gschivley** [comment]
Thanks @sierra-e. I think this is an issue of new resource group file formats and old test systems. I'm working to push a new version of PG and will also update the example systems.

**Comment by gschivley** [comment]
I just merged a new version into the `master` branch with updates to the example systems. A heads up that the systems will be soon moved into their own repository to keep them separate from PowerGenome code.
