### ISSUE TITLE
Check for missing techs in cost_multiplier_technology_map

### ISSUE THREAD

**Issue by gschivley** [PowerGenome/PowerGenome#30]
I've been caught several times by technologies that aren't listed in `cost_multiplier_technology_map`. If a resource isn't included in this table it will have a final investment cost of 0.

Could also assign a default value of 1 and flag for users any technologies that aren't included in the table.

**Comment by fikrikscg** [comment]
@gschivley Is there any update on this issue? I also realized that geothermal and hydropower are not included in cost_multiplier_technology_map. However, investment costs are not zero. That is why, I thought that it may not be a critical issue.

**Comment by gschivley** [comment]
@fikrikscg No, I haven't done anything about it. There is already a function `powergenome.util.check_settings` that checks to make sure 

1. IPM regions aren't misspelled in the `region_aggregations` parameter
2. Model regions are included in the `cost_multiplier_region_map` parameter
3. Model regions are included in the `aeo_fuel_region_map` parameter

The check should go in the same function, probably ensuring that any technologies listed in the parameters `atb_new_gen`, `additional_new_gen`, or `modified_new_gen` are included in `cost_multiplier_technology_map`. The keys in [`cost_multiplier_technology_map` come from this csv](https://github.com/PowerGenome/PowerGenome/blob/27fef8489ab3698d2fe9eb030c59aa637ae1d9ed/data/cost_multipliers/AEO_2020_regional_cost_corrections.csv), which is based on Table 2 in EIA AEO's [Cost and Performance Characteristics of New Generating Technologies](https://web.archive.org/web/20210224000816/https://www.eia.gov/outlooks/aeo/assumptions/pdf/table_8.2.pdf) report.

I'm surprised that not having a match didn't lead to zero investment costs. Investment costs are calculated, then multiplied by regional cost factors. If the technology isn't matched then it should be multiplied by `np.nan`. Will have to investigate further.
