### ISSUE TITLE
Model Tag Issue

### ISSUE THREAD

**Issue by AlannLiu** [PowerGenome/PowerGenome#334]
After including model tag names, the same issue persists:
2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Natural Gas Fired Combined Cycle in region CA does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Natural Gas Fired Combustion Turbine in region CA does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Solar Photovoltaic in region CA does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Natural Gas Fired Combined Cycle in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Natural Gas Fired Combustion Turbine in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Offshore Wind Turbine in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource Solar Photovoltaic in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource NaturalGas_CCAvgCF_Moderate in region CA does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource NaturalGas_CTAvgCF_Moderate in region CA does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource NaturalGas_CCAvgCF_Moderate in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

2024-04-23 23:10:16 [ WARNING] powergenome.GenX:1087

The resource NaturalGas_CTAvgCF_Moderate in region NE does not have any assigned resource tags. Check the 'model_tag_values' and 'regional_tag_values' parameters in your settings file to make sureit is assigned one resource tag type from this list:

['THERM', 'VRE', 'MUST_RUN', 'STOR', 'FLEX', 'HYDRO']

**Comment by gschivley** [comment]
I just did a big merge with code for the new version. The model tag section of code is re-written and now works properly. Looking back at the example settings you shared before, they do seem to be missing `VRE` tags for wind/solar.
