### ISSUE TITLE
PUDL database missing technology_costs_nrelatb table

### ISSUE THREAD

**Issue by NLaws** [PowerGenome/PowerGenome#349]
I've tried the sqlite database in the PowerGenome Google Drive as well as the [PUDL database from Zenodo](https://zenodo.org/records/7472137) that matches the version in the PowerGenome README, but both end up with this error:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: technology_costs_nrelatb
[SQL: 
    SELECT DISTINCT cost_case
    FROM technology_costs_nrelatb
    WHERE
        atb_year == 2022
    ]
```
which comes from the [powergenome/utils.py here](https://github.com/PowerGenome/PowerGenome/blob/719007e7e1f8479191a13948b44f4b5ec05b8565/powergenome/util.py#L344). 

Where do I get the sqlite database with the `technology_costs_nrelatb` table?

**Comment by gschivley** [comment]
This table is in the [`pg_misc` database](https://drive.google.com/file/d/1AT7vsfxLsKuf9N2JXBTlrt2-4I8Rg_hI/view?usp=share_link), not in the PUDL database. Getting all of this on zenodo and properly cited is on my to-do list.
