### ISSUE TITLE
How to update ATB data? Does the repo contain the code used to manipulate raw ATB data?

### ISSUE THREAD

**Issue by NLaws** [PowerGenome/PowerGenome#354]
I would like to use the latest ATB cost data with PowerGenome. However I discovered that the pg_misc_tables_efs_2023.2.sqlite database, technology_costs_nrelatb table has different column names compared to the ATB data and some of the ATB values also appear to have been modifed (e.g. ATB `CAPEX` value in the `core_metric_parameter` column is `capex_mx` in `parameter` column of the PowerGenome table, which must use the ATB `units` column).

Is it possible to get the code used to process the raw ATB data so that I can update the ATB data for use in PowerGenome?

**Comment by gschivley** [comment]
Hi Nick. I haven't gotten around to updating ATB data yet, but [here's the code (renamed as .txt for upload)](https://github.com/user-attachments/files/17248530/atb2023_to_sqlite.txt) that was used last year. A few notes:

- File structure is `CWD/data/<year>`
- The ATBe.parquet file and a custom file -- [NREL_ATB_battery_costs2023.csv](https://github.com/user-attachments/files/17248570/NREL_ATB_battery_costs2023.csv) -- with battery costs split by MW/MWh are in the <year> folder. You'll need to create the battery costs file.
- Watch out for duplicated rows, especially with the new `tax_credit_case` column
- NG tech details are a little crazy this year. I haven't made any decisions about simplifying them vs leaving the same, so it's your choice for now.
- Looks like you can ignore the `_create_hr_table` function in my script.

Let me know if you have any questions.

**Comment by NLaws** [comment]
Thank you @gschivley ! I haven't had a chance to run it yet but I will let you know if I have any questions.
