### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by nspatank** [PowerGenome/PowerGenome#38]
I want to specify region emission constraints using the attached file. I am getting the following error:
`2020-02-24 11:58:25 [    INFO] powergenome.load_profiles:59 Aggregating load curves in grouped regions
Traceback (most recent call last):
  File "//anaconda3/envs/powergenome/bin/run_powergenome_multiple", line 11, in <module>
    load_entry_point('powergenome', 'console_scripts', 'run_powergenome_multiple')()
  File "/D/PowerGenome/powergenome/run_powergenome_multiple_outputs_cli.py", line 517, in main
    genx_settings = make_genx_settings_file(pudl_engine, _settings)
  File "/D/PowerGenome/powergenome/GenX.py", line 170, in make_genx_settings_file
    if policies.loc[(case_id, model_year), "region"] == "all":
  File "//anaconda3/envs/powergenome/lib/python3.7/site-packages/pandas/core/generic.py", line 1555, in __nonzero__
    self.__class__.__name__
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

[rps_ces_emission_limits_regional.xlsx](https://github.com/gschivley/PowerGenome/files/4245753/rps_ces_emission_limits_regional.xlsx)

**Comment by gschivley** [comment]
One solution to problems with smart defaults would be to make a user specify all of these values in the file `case_genx_settings_fn`. @nspatank do you think there's value in a system of smart defaults instead of making the user specify GenX settings for each case?

**Comment by nspatank** [comment]
I think there is some value to it.

**Comment by gschivley** [comment]
Closing because I think this issue is no longer relevant.
