### ISSUE TITLE
about rounding of certain parameters

### ISSUE THREAD

**Issue by nspatank** [PowerGenome/PowerGenome#75]
We don't want to round up_time, down_time, and Max_DSM_delay parameters in the run_powergenome_multiple_outputs_cli.py file. Could you please remove them from the COL_ROUND_VALUES dictionary in the GenX.py file? GenX throws an error if they have float value instead of integer

**Comment by gschivley** [comment]
@nspatank It looks like you took care of this in 50d2f2525449b0c95a721fb17bb79c37b8fd90b5. Should those columns be added to the `INT_COLS` list in GenX.py?
