### ISSUE TITLE
model_tag_values does not tag some technologies correctly

### ISSUE THREAD

**Issue by fikrikscg** [PowerGenome/PowerGenome#91]
New_Build column in the generator data frame has some anomalies. For instance, although I say

model_tag_values:
     New_Build:
          Natural Gas: 1

in settings file, natural_gas_fired_combined_cycle and natural_gas_fired_combustion_turbine have 0 in New_Build column of the data frame. I thought that it would be enough to write Natural Gas: 1 in model_tag_values because str.contains() will do the job and make every natural gas 1.

There was a similar problem for Landbased Wind. It is a new resource according to atb_new_gen parameter, but New_Build column of generator data frame had 0 for this resource. I checked New_Build of model_tag_values parameter and it was Landbased Wind: 1. I removed the space and made it LandbasedWind: 1. After running this, New_Build column turned to 1 for this resource.

**Comment by gschivley** [comment]
The string matching includes spaces. Existing resource names are based on EIA technology names and have spaces. New-build resource names are based on <technology>_<tech_detail> from ATB. So `Natural Gas` is a good string match for existing `Natural Gas Combined Cycle` or `Natural Gas Combustion Turbine`. And `NaturalGas` is a match for `NaturalGas_CTavg`.

Capitalization is ignored in the string matching.

You can take a look at the associated code [here](https://github.com/PowerGenome/PowerGenome/blob/cf0f5fdb888057918245860b0edbf8c632c5b602/powergenome/generators.py#L1216-L1238).

**Comment by gschivley** [comment]
@fikrikscg Did this solve your problem? If so, I'm going to close the issue.

**Comment by fikrikscg** [comment]
Yes, it solved the problem. Thank you for the clarification.

I have a related question. I realized that there are some generators both in EIA (existing resources) and ATB (new build resources) with spaces in their names. For instance, existing coal unit has a name of "Coal Integrated Gasification Combined Cycle" and new build resource has name of "Coal" and technology detail is "newAvgCF". How do I distinguish existing and new build resources? Something like the following?

New_Build:
     Coal Integrated: 0
     Coal newAvgCF: 1

**Comment by fikrikscg** [comment]
Okay, I understand. Correct format for new build resources is Coal_newAvgCF or CoalnewAvgCF for the above example. You can close the issue.
