### ISSUE TITLE
Naming of some columns in Network.csv output file

### ISSUE THREAD

**Issue by fikrikscg** [PowerGenome/PowerGenome#95]
This is a small issue. "Region description" and "Transmission Path Name" columns in Network.csv output file have spaces in their names. It might be harder to handle it while loading this data and accessing columns in programming languages such as Julia.

**Comment by gschivley** [comment]
We have plans to create a native set of PG output files that won't be tied to any specific model, and I'll be making all of those column names snake case. In this case I think that the columns aren't used by GenX -- they were just added to make things easier for humans to read.

How does Julia deal with spaces in column names? There are tons of data sources out there with spaces (e.g. every EIA excel file).

**Comment by fikrikscg** [comment]
Julia accesses column names with spaces with `Symbol` statement. For instance, I have to write `network[:,Symbol("Region description")]` to access region description column. Again, this is not a big issue, but one has to track whether column name has spaces or not.

**Comment by gschivley** [comment]
Version 0.5.0 of PowerGenome will have outputs designed to work with the open-source version of GenX, and should solve this issue. That code has been released as [v0.5.0-beta.1](https://github.com/PowerGenome/PowerGenome/releases/tag/v0.5.0-beta.1). It isn't a final release yet, but I'm going to close this issue.
