### ISSUE TITLE
Some new build resources do not show up in generator data set

### ISSUE THREAD

**Issue by fikrikscg** [PowerGenome/PowerGenome#98]
I would like to add all geothermal new build resources with all technology details as shown in the following example:

atb_new_gen:
     - [Geothermal, HydroFlash, Mid, 500]
     - [Geothermal, HydroBinary, Mid, 500]
     - [Geothermal, NFEGSBinary, Mid, 500]
     - [Geothermal, DeepEGSFlash, Mid, 500]
     - [Geothermal, DeepEGSBinary, Mid, 500]

However, only a few of them show up in generator data set. More interestingly, when I change the order above, a different set of geothermal resources show up in the data set.

Similarly, none of Hydropower new build resources show up in generator data set.

**Comment by gschivley** [comment]
Thanks for bringing this up, I'll have to check it out. Is there a reason you're allowing all of the geothermal technologies at the same time?

**Comment by fikrikscg** [comment]
No, there is no specific reason. I just wanted to check if I can include all geothermal resources. As a related question, is it enough for me to select only one of these geothermal resources (e.g. only HydroFlash) and ignore the rest?

**Comment by gschivley** [comment]
Usually one is the cheapest. There might be regional deployment restrictions so that one technology can be installed in Region 1 but not in Region 2, so that might be a reason to include multiple. But ATB costs are high enough that Geothermal doesn't usually get built unless you are trying to hit 0 carbon and don't allow nuclear or CCS.

I noticed that the `test_settings` file doesn't have geothermal in `cost_multiplier_technology_map`. Unlikely that it is the root cause, but you should make sure that it's in there. You can check out the [csv where this data is stored](https://github.com/PowerGenome/PowerGenome/blob/master/data/cost_multipliers/AEO_2020_regional_cost_corrections.csv) to see what the EIA technology names are.

```
cost_multiplier_technology_map:
  Ultra-supercritical coal (USC): [Coal_newAvgCF, Coal_newHighCF]
  # IGCC: [Coal_IGCCAvgCF, Coal_IGCCAvgCF]
  USC with 30% CCS: [Coal_CCS30AvgCF, Coal_CCS30HighCF]
  USC with 90% CCS: Coal_CCS90AvgCF, Coal_CCS90HighCF]
  CT - aeroderivative: []
  CT - industrial frame: [NaturalGas_CTAvgCF, NaturalGas_CTHighCF]
  CC - single shaft: []
  CC - multi shaft: [NaturalGas_CCAvgCF, NaturalGas_CCHighCF]
  CC with 90% CCS: [NaturalGas_CCCCSAvgCF, NaturalGas_CCCCSHighCF, NGCCS100, NaturalGas_CCS100, NaturalGas_CCS100_low,NaturalGas_CCS100_high ]
  Fuel cells: []
  Advanced nuclear: [Nuclear_*, Nuclear_mid, Nuclear_low, Nuclear_high]
  Biomass: [Biopower_CofireOld, Biopower_CofireNew, Biopower_Dedicated]
  MSW - landfill gas: []
  Wind: [LandbasedWind]
  Wind offshore: [OffShoreWind]
  Solar thermal: [CSP]
  Solar PV - tracking: [UtilityPV, CommPV, ResPV]
  Battery storage: [Battery_*]
  Geothermal: [Geothermal_]
```

**Comment by fikrikscg** [comment]
`cost_multiplier_technology_map:
  Ultra-supercritical coal (USC): [Coal_newAvgCF, Coal_newHighCF]
  # IGCC: [Coal_IGCCAvgCF, Coal_IGCCHighCF]
  USC with 30% CCS: [Coal_CCS30AvgCF, Coal_CCS30HighCF]
  USC with 90% CCS: Coal_CCS90AvgCF, Coal_CCS90HighCF]
  CT - aeroderivative: []
  CT - industrial frame: [NaturalGas_CTAvgCF, NaturalGas_CTHighCF]
  CC - single shaft: []
  CC - multi shaft: [NaturalGas_CCAvgCF, NaturalGas_CCHighCF]
  CC with 90% CCS: [NaturalGas_CCCCSAvgCF, NaturalGas_CCCCSHighCF]
  Fuel cells: []
  Advanced nuclear: [Nuclear_*]
  Biomass: [Biopower_CofireOld, Biopower_CofireNew, Biopower_Dedicated]
  MSW - landfill gas: []
  Wind: [LandbasedWind]
  Wind offshore: [OffShoreWind]
  Solar thermal: [CSP]
  Solar PV - tracking: [UtilityPV, CommPV, ResPV]
  Battery storage: [Battery_*]
  Geothermal: [Geothermal_*]
  Internal combustion engine: [Coal_IGCCAvgCF, Coal_IGCCHighCF]
  Dist. Generation base: []
  Dist. Generation - peak: []
  Conventional hydropower: [Hydropower_*]`

**Comment by gschivley** [comment]
Sorry for the delay, I'll look into this.

**Comment by fikrikscg** [comment]
Okay, thank you.

**Comment by gschivley** [comment]
That was a tough one to track down! Turns out that when the `resource_clusters` module was designed, hydro was classified as a renewable like wind or solar that needs resource group files. Probably because of how we treated existing hydro profiles. Without the resource group files, hydro doesn't show up in the results. I don't have data on the resource potential or generation profile of various hydro resources across the US, so the quickest solution is to comment out [lines in this section](https://github.com/PowerGenome/PowerGenome/blob/d9ffbde76ae64b7ad9e2eef62998b687b1c75857/powergenome/resource_clusters.py#L31-L57) related to hydro. In the meantime I'll think about how to handle this.

**Comment by fikrikscg** [comment]
Thank you for the resolution. But, I still could not see new build hydropower in generator data set. Errors occur.

Could you please tell me what I should step by step? For instance, as far as I understand, I need to add hydropower under `relewables_clusters` parameter, like

`renewables_clusters:
  - region: NorCal
    technology: hydro
    max_clusters: 1
    min_capacity: ~
    max_lcoe: ~`

Then, what should I do? Should I comment out the following lines:

`("hydropower", None): {"technology": "hydro"},` under NREL_ATB_TECHNOLOGY_MAP in resource_clusters.py

`"conventionalhydroelectric": {"technology": "hydro", "small": False},
    "smallhydroelectric": {"technology": "hydro", "small": True},` under EIA_TECHNOLOGY_MAP in resource_clusters.py

Eventually, I would like to see new build hydropower in generator data set. I have resource potentials. I can insert in manually. Also, I can copy and paste existing hydropower variability into new build hydropowers' variability columns.

**Comment by fikrikscg** [comment]
Just to be clear, PowerGenome was working without any error, but I am not able to see hydropower in `Generators_data.csv`. As per your suggestion, when I added hydropower like below

```
renewables_clusters:
    region: NorCal
    technology: hydro
    max_clusters: 1
    min_capacity: ~
    max_lcoe: ~
```

I thought it would show up in `Generators_data.csv`, but it did not.

**Comment by fikrikscg** [comment]
Okay, you can forget about my previous comments :) It seems that I misunderstood what you suggested. I thought you suggested me to add it to `renewables_clusters` parameter, but I was wrong.

I just commented out lines 

`("hydropower", None): {"technology": "hydro"}`, under `NREL_ATB_TECHNOLOGY_MAP` in resource_clusters.py

and 

```
"conventionalhydroelectric": {"technology": "hydro", "small": False},
"smallhydroelectric": {"technology": "hydro", "small": True},
```

under `EIA_TECHNOLOGY_MAP` in resource_clusters.py.

Now, I see new build hydropower resources. By the way, investment cost is 0 for all new build hydro except with npd1 technology detail.

**Comment by fikrikscg** [comment]
A note for people who might have the same issue:

Only

`("hydropower", None): {"technology": "hydro"},` under `NREL_ATB_TECHNOLOGY_MAP` in resource_clusters.py

should be commented out. If the second set of lines above (under `EIA_TECHNOLOGY_MAP`) is commented out, the existing hydro units' generator profile will vanish.

**Comment by gschivley** [comment]
Thanks for the note. I'm very busy through next week but will be opening an issue related to this. I also have some news of big updates in the pipeline that I'll be sharing on the mailing list.
